vscode:
  extensions:
    - JamesBirtles.svelte-vscode@0.4.0:aicIqbjKmEBw3n8OhIUmwA==

tasks:
  - init: >
      touch /tmp/.npm-lock &&
      npm install &&
      rm /tmp/.npm-lock
    command: npm run build